version: '3.8'

services:
  movies.api:
    image: ${DOCKER_REGISTRY-}moviesapi
    container_name: movies.api
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
    - "5000:5000"
    - "5001:5001"
    depends_on:
    - movies.db
    - movies.cache

  movies.db:
    image: postgres:13
    container_name: movies.db
    environment:
      POSTGRES_USER: loc-pg-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: MoviesDb 
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  movies.cache:
    image: redis:latest
    container_name: movies.cache
    restart: always
    ports:
    - 6379:6379
volumes:  
  dbdata: 
 
